### ISSUE TITLE
Feature request: forecast --end-date

### ISSUE THREAD

**Issue by nicholascapo** [github/gh-actions-importer#224]
# Feature Request

Add a `--end-date` flag to `forecast`, that can be used with `--start-date` to calculate an arbitrary time window.

## Problem 

`forcast` has a `--start-date` flag, but no `--end-date` flag.
This makes it hard to calculate numbers for a date range (for example: a whole calendar month).

Example: to generate forecasts for June (2023-06) and July (2023-07):

- wait until 2023-08-01
- run a forecast with `--start-date=2023-07-01`
- run a forecast with `--start-date=2023-06-01`
- for each value in the June report:
  - subtract the value from the July report

However there is still some inaccuracy, since if I run the second report later in the day (or later in the month) it will include more of that day (or month).

## Requested Feature

To generate forecasts for June (2023-06) and July (2023-07):
```shell
gh actions-importer forecast --start-date=2023-07-01 --end-date=2023-08-01 --output-dir=july
gh actions-importer forecast --start-date=2023-06-01 --end-date=2023-07-01 --output-dir=june
```

**Comment by luke-engle** [comment]
We wanted to implement this feature when forecast was initially developed, but ultimately scrapped it because unfortunately most providers don't provide an api parameter that allows specifying a date to begin pipeline/build fetching. If we did implement something like this, it could result in performance issues because we'd have to fetch everything from the current date, and then throw away all the recent results.

For instance, if you wanted jobs from 2020-01-01 - 2020-02-01, we would have to fetch and throw away all jobs from 2020-02-02 - 2023-08-03, which would be a lot of extra work and could make the program hang for an extended period.

Because of this, I'm sorry to say we won't be implementing this feature 😞  However, at the end of a forecast run, we output 1-N `<output_dir>/jobs/<date-time>_jobs_N.json` files which contain the raw job data. You can use the `start_time` in these jobs files to manually delete any entries that aren't in your desired range. You can then run the forecast command a second time with the `--source-file-path` command-line option to specify the job file(s) to include in the forecast (for instance, `gh actions-importer forecast --source-file-path tmp/jobs/* -o tmp`). That second forecast run will not make any API calls and will give you an accurate report for the date range desired, assuming all jobs outside the desired range were removed.
